main_dir: "/home/udmmp/Desktop/Uri/Analyze_Mane_Clinical"
docker_yaml_file : "yaml_files/docker_resources.yaml"
annotations_yaml_file : "yaml_files/annotation_resources_hg19.yaml"
reference_yaml_file : "yaml_files/reference_resources.yaml"
runs_dir: "/ngs-results/"
runs_analyzed_yaml: "/home/udmmp/Desktop/Uri/Analyze_Mane_Clinical/yaml_files/runs_analyzed.yaml"
log_path: "/home/udmmp/Desktop/Uri/Analyze_Mane_Clinical/mane_clinical.log"
bed_path: "/home/udmmp/Desktop/Uri/Analyze_Mane_Clinical/sorted_mane_clinical_AGILENT_GLOBAL_gatk.bed"
ref_fasta_path: "/raw-data/ANNOTATIONS/REF_DIR/hg19/ucsc.hg19.fasta"
