main_dir: "/home/ocanal/Desktop/Mane_clinical"
docker_yaml_file : "yaml_files/docker_resources.yaml"
annotations_yaml_file : "yaml_files/annotation_resources_hg19.yaml"
reference_yaml_file : "yaml_files/reference_resources.yaml"
runs_dir: "/home/ocanal/Desktop/vep_with_gff"
runs_analyzed_yaml: "/home/ocanal/Desktop/Mane_clinical/yaml_files/runs_analyzed.yaml"
log_path: "/home/ocanal/Desktop/vep_with_gff/mane_clinical.log"
bed_path: "/home/ocanal/Desktop/Mane_clinical/sorted_mane_clinical_AGILENT_GLOBAL_gatk.bed"
ref_fasta_path: "/home/ocanal/REF_DIR/hg19/ucsc.hg19.fasta"